### ISSUE TITLE
 Errand `register_admin_ui' doesn't exist

### ISSUE THREAD

**Issue by jamesecahill** [cloudfoundry-community/admin-ui-boshrelease#12]
I'm getting an error stating that this errand doesn't exist. I manually ran the uaac steps from https://github.com/cloudfoundry-incubator/admin-ui, and it seems to have given access to DEA, apps, and a couple other things. But I'm still getting "This page requires data from services that are currently unavailable" on the orgs page, and a could others. Any idea why the errand doesn't exist? Maybe I used an outdated bosh release? I used the one from the README at https://admin-ui-boshrelease.s3.amazonaws.com/boshrelease-admin-ui-3.tgz.

**Comment by RickvdP** [comment]
I actually have the exact same thing. I'm not able to explain why the errand is not found in the release, as I'm not that familiar with bosh. Running the ```uaac``` commands manually indeed gives basic access to the UI, but a lot of pages give the ```This page requires data from services that are currently unavailable``` error.

In other words, +1 for this issue and any help would be appreciated.

**Comment by RickvdP** [comment]
Okay, so this was actually quite easy to fix. As suggested in https://github.com/cloudfoundry-incubator/admin-ui/issues/89 the issue was that those specific tabs try to fetch data over HTTPS, which won't work out of the box with self-signed certificates provided by bosh-lite. 

Fixing it is rather easy though: you need to add ```cloud_controller_ssl_verify_none: true``` to your release manifest, which will make it look somewhat like this

```
properties:
  admin_ui:
    cloud_controller_uri: https://api.x.x.x.x.xip.io
    cloud_controller_ssl_verify_none: true
    uaa_admin_credentials:
      password: admin
      username: admin
    ui_admin_credentials:
      password: admin
      username: admin
    ui_credentials:
      password: user
      username: user
    uri: admin.x.x.x.x.xip.io
```

By running
```
bosh deployment releases/<your deployment>.yml
bosh deploy
# verify and accept changes
```
Your changes will be applied and deployed. **Note** that the first time you access the admin UI the tabs that used to work like DEA and Apps might now give you an error. Just give it a couple of minutes (~5) to pull in the first data. After this all tabs should work.

@jamesecahill I highly doubt you're still looking into this, but anyway: ping :)
